### ISSUE TITLE
Create a code review checklist

### ISSUE THREAD

**Issue by jamesfernando94** [Gregam3/ASEGroup1#202]
Create a code review checklist to improve code quality in the repository and a pull request template to better help merge messages and information stored in the git history

**Comment by jamesfernando94** [comment]
Planning:
- [ ] Create a wiki page for the code review checklist
- [ ] Do some research into general code review checklists
- [ ]  Look into java/spring boot code review checklists
- [ ] Look into react code review checklists
- [ ] Compile a code review checklist and have it approved by everyone
- [ ] Look at some general pull request templates
- [ ] Create a pull request template and add it to the repository
